exports.STARTING_ATTRIBUTE_POINTS = 5;
exports.STARTING_ABILITY_POINTS = 5;
exports.BASE_ATTRIBUTE_POINTS = 5;
exports.MAX_ATTRIBUTE_POINTS = 15;
exports.MAX_ABILITY_POINTS = 5;
exports.MAX_LEVEL = 20;